### PR TITLE
Theme Toggler Hydration Warning Handled

### PR DESCRIPTION
**Pull request by walleeva2018**
### What is Added 
- In Navbar View Theme Switcher which should be a client-side component was rendering as a Server side component. Fixed that

### CODE REVIEW

**Comment by romangg** [comment]
Alternative is to use `v-show` instead of `v-if`. I think I would prefer that as more can be statically generated this way. What do you think?

**Comment by walleeva2018** [comment]
> Alternative is to use `v-show` instead of `v-if`. I think I would prefer that as more can be statically generated this way. What do you think?

Yeah As Its navbar the load time will be faster. I will update that

**Comment by walleeva2018** [comment]
@romangg Let me know if there is any problem

**Comment by romangg** [comment]
With the v-show the change to ClientOnly is not needed anymore. So this change needs to be removed from the branch/PR.

**Comment by romangg** [comment]
The cleanest solution is to use interactive rebase for that: https://git-rebase.io/

**Comment by walleeva2018** [comment]
> With the v-show the change to ClientOnly is not needed anymore. So this change needs to be removed from the branch/PR.

Yeah My bad. Is it okay now?

**Comment by romangg** [comment]
Thanks for the update. The problem is that this revision still contains changes that are as far as I see not needed anymore.

**Pull request merged**
