### PR TITLE
content: use a more current screenshot for sway

### PR DESCRIPTION
**Pull request by boredland**
the one currently used was really dated.

### CODE REVIEW

**Comment by romangg** [comment]
Use "content" commit type.

**Comment by boredland** [comment]
Will do, but not supporting the conventional commit subjects is very confusing.

**Comment by romangg** [comment]
Hmm, I agree as the chore type is actually [recommended](https://www.conventionalcommits.org/en/v1.0.0/#summary). There had been some discussion in the past of removing it because people tend to use it for everything. But as of right now it's still recommended.

**Comment by romangg** [comment]
See discussion here: https://github.com/conventional-commits/conventionalcommits.org/issues/303

**Comment by boredland** [comment]
> Hmm, I agree as the chore type is actually [recommended](https://www.conventionalcommits.org/en/v1.0.0/#summary). There had been some discussion in the past of removing it because people tend to use it for everything. But as of right now it's still recommended.

Well, ya. Because enforcing commit messages is just... not that important IMO. Especially if one just squashes those on merge, which I often do. But never-mind, just amended.

**Comment by romangg** [comment]
Yea, I'll go over them at some point again. I also just noticed I have a "content" type and scope, which doesn't make sense.

Thanks for the updated screenshot!

**Pull request merged**
