### PR TITLE
fix: prerender issue for pagination component

### PR DESCRIPTION
**Pull request by nurRiyad**

### CODE REVIEW

**Comment by romangg** [comment]
It would be good if `manjaro.org/news` is page 1, and then for other pages it is `manjaro.org/news/page/2` and so on. Also `manjaro.org/news/page/1` should forward to `manjaro.org/news`.

I've done something similar at [another site of mine](https://subdiff.org/blog). What do you think?

**Comment by nurRiyad** [comment]
Thanks for the review. Will update soon.

**Comment by nurRiyad** [comment]
@romangg I have updated the pagination components.

**Comment by romangg** [comment]
Works great! I changed from `news/pages/...` to `news/page/...`, other than that let's merge it. Thanks  @nurRiyad!

Closes #40

**Pull request merged**
